window.Akay = window.Akay || {};

window.Akay.PRODUCTS = [
  {
    id: "badem",
    title: "Kavrulmuş Badem",
    category: "kuruyemis",
    priceLabel: "₺85 / 250g",
    priceNumeric: 85,
    short: "Doğal, tuzsuz ve taptaze badem.",
    desc: "Özenle seçilmiş bademlerimiz, hafif kavrulup doğal lezzeti korunacak şekilde paketlenir. Kahvaltı ve atıştırmalıklar için ideal.",
    rating: 4.9,
    reviews: 182,
    origin: "Ege Bölgesi",
    delivery: "24 saatte kargoda",
    img: "images/badem.jpg",
    facts: ["Kaynak: Ege", "Tazelik: 7 gün içinde paketlenmiş", "Alerjen: Evet"]
  },
  {
    id: "findik",
    title: "Giresun Fındığı",
    category: "kuruyemis",
    priceLabel: "₺90 / 250g",
    priceNumeric: 90,
    short: "Karadeniz’in en lezzetli fındıkları.",
    desc: "Giresun bölgesinden seçilen fındıklarımız, çekirdek kalite kontrolünden geçer. Tatlı tariflerde ve atıştırmalıkta mükemmel.",
    rating: 4.8,
    reviews: 156,
    origin: "Giresun",
    delivery: "48 saatte kargoda",
    img: "images/findik.jpg",
    facts: ["Kaynak: Giresun", "Tazelik: 10 gün içinde paketlenmiş", "Alerjen: Evet"]
  },
  {
    id: "fistik",
    title: "Antep Fıstığı",
    category: "cekirdek",
    priceLabel: "₺120 / 250g",
    priceNumeric: 120,
    short: "Gaziantep’ten gelen birinci kalite fıstık.",
    desc: "Doğal yöntemlerle kurutulmuş Antep fıstıkları. Tatlı ve tuzlu mutfaklar için yüksek kalite.",
    rating: 5,
    reviews: 210,
    origin: "Gaziantep",
    delivery: "24 saatte kargoda",
    img: "images/fistik.jpg",
    facts: ["Kaynak: Gaziantep", "Tazelik: 14 gün içinde paketlenmiş", "Alerjen: Evet"]
  },
  {
    id: "ceviz",
    title: "İç Ceviz",
    category: "kuruyemis",
    priceLabel: "₺70 / 250g",
    priceNumeric: 70,
    short: "Sağlıklı ve taptaze iç ceviz.",
    desc: "Protein ve sağlıklı yağ deposu olan cevizlerimiz tazeliği korunarak paketlenir. Tatlı ve yemeklerde kullanılmaya uygundur.",
    rating: 4.7,
    reviews: 132,
    origin: "İç Anadolu",
    delivery: "48 saatte kargoda",
    img: "images/ceviz.jpg",
    facts: ["Kaynak: İç Anadolu", "Tazelik: 12 gün içinde paketlenmiş", "Alerjen: Evet"]
  },
  {
    id: "kaju",
    title: "Kaju",
    category: "cekirdek",
    priceLabel: "₺95 / 250g",
    priceNumeric: 95,
    short: "En kaliteli kaju fıstığı.",
    desc: "Kaju fıstıklarımız, tat ve doku açısından premium sınıftadır. Atıştırmalık ve yemeklerde çok yönlü kullanım.",
    rating: 4.9,
    reviews: 164,
    origin: "Hindistan",
    delivery: "48 saatte kargoda",
    img: "images/kaju.jpg",
    facts: ["Kaynak: Tropik", "Tazelik: 20 gün içinde paketlenmiş", "Alerjen: Evet"]
  },
  {
    id: "fistik-yerli",
    title: "Yer Fıstığı",
    category: "cekirdek",
    priceLabel: "₺50 / 250g",
    priceNumeric: 50,
    short: "Kavrulmuş ve çıtır çıtır yer fıstığı.",
    desc: "Küçük parti kavurma ile çıtırlık korunur. Atıştırmalık keyfi için lezzetli bir seçenek.",
    rating: 4.6,
    reviews: 118,
    origin: "Çukurova",
    delivery: "72 saatte kargoda",
    img: "images/fistik-yerli.jpg",
    facts: ["Kaynak: İç Anadolu", "Tazelik: 8 gün içinde paketlenmiş", "Alerjen: Evet"]
  },
  {
    id: "karisik-1",
    title: "Karışık Kuruyemiş A",
    category: "karisik",
    priceLabel: "₺150 / 250g",
    priceNumeric: 150,
    short: "Badem, fındık, fıstık ve ceviz karışımı.",
    desc: "En sevilen lezzetlerin karışımı; dengeli tat ve doku sunar. Parti ve misafirler için ideal.",
    rating: 5,
    reviews: 264,
    origin: "Anadolu Çiftlikleri",
    delivery: "24 saatte kargoda",
    img: "images/karisik-1.jpg",
    facts: ["Karışım: Badem, Fındık, Fıstık, Ceviz", "Tazelik: 7 gün", "Ambalaj: Vakumlu"]
  },
  {
    id: "karisik-2",
    title: "Karışık Kuruyemiş B",
    category: "karisik",
    priceLabel: "₺170 / 250g",
    priceNumeric: 170,
    short: "Özel harman karışım, kuruyemiş şöleni.",
    desc: "Özel baharat ve az tuz ile harmanlanmış seçkin karışım. Atıştırmalık için hazırlanmıştır.",
    rating: 4.9,
    reviews: 198,
    origin: "Akdeniz",
    delivery: "24 saatte kargoda",
    img: "images/karisik-2.jpg",
    facts: ["Karışım: Kaju, Antep, Badem", "Tazelik: 5 gün", "Ambalaj: Hava korumalı"]
  },
  {
    id: "badem-tuzlu",
    title: "Tuzlu Kavrulmuş Badem",
    category: "kuruyemis",
    priceLabel: "₺88 / 250g",
    priceNumeric: 88,
    short: "Hafif tuzlu özel kavurma badem.",
    desc: "Hafif tuz dengesi ile kavrulmuş bademlerimiz, çay saatleri ve atıştırmalıklar için idealdir.",
    rating: 4.8,
    reviews: 174,
    origin: "Ege Bölgesi",
    delivery: "24 saatte kargoda",
    img: "images/badem.jpg",
    facts: ["Tuz: Deniz tuzu", "Tazelik: 6 gün", "Ambalaj: Kilitli poşet"]
  },
  {
    id: "cekirdek-karisik",
    title: "Çekirdek Karışık (Ay çekirdeği vb.)",
    category: "cekirdek",
    priceLabel: "₺60 / 250g",
    priceNumeric: 60,
    short: "Ay çekirdeği, kabak çekirdeği karışımı.",
    desc: "Çerez keyfi için doğal ve kavrulmuş çekirdekler harmanlanmıştır. Spor sonrası atıştırmalık olarak tercih edilir.",
    rating: 4.5,
    reviews: 98,
    origin: "Trakya",
    delivery: "72 saatte kargoda",
    img: "images/karisik-2.jpg",
    facts: ["Karışım: Ay çekirdeği, Kabak çekirdeği", "Tuz: Az", "Ambalaj: Kilitli"]
  }
];

window.Akay.FAVORITES_KEY = 'akay_fav_v1';
